use redis::AsyncCommands;
use sqlx::postgres::PgPoolOptions;
// Simplified logic: Listen to Redis Trades -> Insert into TimescaleDB

pub mod exchange_proto {
    // This pulls in the code generated by build.rs in the target folder
    include!(concat!(env!("OUT_DIR"), "/exchange.rs"));
}


#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let db_url = std::env::var("DATABASE_URL").expect("DATABASE_URL must be set");
    let redis_url = std::env::var("REDIS_URL").expect("REDIS_URL must be set");
    let db_queue : &'static str = "db_processor";

    // 1. Connect to TimescaleDB
    let pool = PgPoolOptions::new()
        .max_connections(10)
        .connect(&db_url).await?;

    let client = redis::Client::open(redis_url)?;
    let mut conn = client.get_multiplexed_async_connection().await?;
    println!("DB worker online: Connected to redis and timescaledb");

    loop {
        let raw_data:Option<Vec<u8>> = conn.rpop(db_queue, None).await?;
        println!("{:?}", raw_data);
    }
    
    Ok(())
}