use std::{str::FromStr, time::{Duration, Instant}};

use chrono::{TimeZone, Utc};
use prost::Message;
use redis::AsyncCommands;
use rust_decimal::Decimal;
use sqlx::{QueryBuilder, postgres::PgPoolOptions};
// Simplified logic: Listen to Redis Trades -> Insert into TimescaleDB

pub mod exchange_proto {
    // This pulls in the code generated by build.rs in the target folder
    include!(concat!(env!("OUT_DIR"), "/exchange.rs"));
}


#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let db_url = std::env::var("DATABASE_URL").expect("DATABASE_URL must be set");
    let redis_url = std::env::var("REDIS_URL").expect("REDIS_URL must be set");
    let db_queue : &'static str = "db_processor";

    // 1. Connect to TimescaleDB
    let pool = PgPoolOptions::new()
        .max_connections(10)
        .connect(&db_url).await?;
    // RUN migrations on startup
    sqlx::migrate!("./migrations")
        .run(&pool)
        .await?;
    let client = redis::Client::open(redis_url)?;
    let mut conn = client.get_multiplexed_async_connection().await?;
    println!("DB worker online: Connected to redis and timescaledb");

    // ------------------------------BATCHING CONFIG---------------------
    let mut trade_buffer = Vec::with_capacity(1000);
    let mut last_flush = Instant::now();
    let max_batch_size = 500;
    let max_wait_time = Duration::from_millis(100);


    loop {
        // 1. NON-BLOCKING DRAIN: Pull as many items as possible from Redis quickly
        // This keeps the Redis queue empty and memory-resident
        while let Ok(Some(bytes)) = conn.rpop::<_, Option<Vec<u8>>>(db_queue, None).await {
            if let Ok(trade) = exchange_proto::Trade::decode(&bytes[..]) {
                trade_buffer.push(trade);
            }
            // Don't stay in this while loop forever if Redis is slammed
            if trade_buffer.len() >= max_batch_size { break; }
        }

        // 2. THE LOGIC FIX: Check if we SHOULD flush
        let should_flush = !trade_buffer.is_empty() && 
            (trade_buffer.len() >= max_batch_size || last_flush.elapsed() >= max_wait_time);

        if should_flush {
            let mut query_builder = QueryBuilder::new(
                "INSERT INTO trade_history (time, symbol, price, volume, taker_side) "
            );

            query_builder.push_values(trade_buffer.iter(), |mut b, trade| {
                let datetime = Utc.timestamp_micros(trade.timestamp as i64).unwrap();
                let price = Decimal::from_str(&trade.price).unwrap_or(Decimal::ZERO);
                let quantity = Decimal::from_str(&trade.quantity).unwrap_or(Decimal::ZERO);
                let side_str = if trade.taker_side == exchange_proto::Side::Buy as i32 { "BUY" } else { "SELL" };
                let symbol = format!("{:?}_{:?}", trade.base, trade.quote);

                b.push_bind(datetime)
                 .push_bind(symbol)
                 .push_bind(price)
                 .push_bind(quantity)
                 .push_bind(side_str);
            });

            let query = query_builder.build();
            if let Err(e) = query.execute(&pool).await {
                eprintln!("Database insert error: {}", e);
            }

            trade_buffer.clear();
            last_flush = Instant::now();
        }

        // 3. ADAPTIVE SLEEP: Only sleep if there's nothing to do
        if trade_buffer.is_empty() {
            tokio::time::sleep(Duration::from_millis(10)).await;
        }
    }
    
    Ok(())
}