// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.12.4
// source: exchange.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "exchange";

export enum Side {
  BUY = 0,
  SELL = 1,
  UNRECOGNIZED = -1,
}

export function sideFromJSON(object: any): Side {
  switch (object) {
    case 0:
    case "BUY":
      return Side.BUY;
    case 1:
    case "SELL":
      return Side.SELL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Side.UNRECOGNIZED;
  }
}

export function sideToJSON(object: Side): string {
  switch (object) {
    case Side.BUY:
      return "BUY";
    case Side.SELL:
      return "SELL";
    case Side.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OrderType {
  LIMIT = 0,
  MARKET = 1,
  UNRECOGNIZED = -1,
}

export function orderTypeFromJSON(object: any): OrderType {
  switch (object) {
    case 0:
    case "LIMIT":
      return OrderType.LIMIT;
    case 1:
    case "MARKET":
      return OrderType.MARKET;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderType.UNRECOGNIZED;
  }
}

export function orderTypeToJSON(object: OrderType): string {
  switch (object) {
    case OrderType.LIMIT:
      return "LIMIT";
    case OrderType.MARKET:
      return "MARKET";
    case OrderType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum AssetId {
  ASSET_UNKNOWN = 0,
  BTC = 1,
  ETH = 2,
  USDT = 3,
  UNRECOGNIZED = -1,
}

export function assetIdFromJSON(object: any): AssetId {
  switch (object) {
    case 0:
    case "ASSET_UNKNOWN":
      return AssetId.ASSET_UNKNOWN;
    case 1:
    case "BTC":
      return AssetId.BTC;
    case 2:
    case "ETH":
      return AssetId.ETH;
    case 3:
    case "USDT":
      return AssetId.USDT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AssetId.UNRECOGNIZED;
  }
}

export function assetIdToJSON(object: AssetId): string {
  switch (object) {
    case AssetId.ASSET_UNKNOWN:
      return "ASSET_UNKNOWN";
    case AssetId.BTC:
      return "BTC";
    case AssetId.ETH:
      return "ETH";
    case AssetId.USDT:
      return "USDT";
    case AssetId.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum MarketId {
  MARKET_UNKNOWN = 0,
  /** BTC_USDT - Base: BTC (1), Quote: USDT (3) */
  BTC_USDT = 1,
  /** ETH_USDT - Base: ETH (2), Quote: USDT (3) */
  ETH_USDT = 2,
  UNRECOGNIZED = -1,
}

export function marketIdFromJSON(object: any): MarketId {
  switch (object) {
    case 0:
    case "MARKET_UNKNOWN":
      return MarketId.MARKET_UNKNOWN;
    case 1:
    case "BTC_USDT":
      return MarketId.BTC_USDT;
    case 2:
    case "ETH_USDT":
      return MarketId.ETH_USDT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MarketId.UNRECOGNIZED;
  }
}

export function marketIdToJSON(object: MarketId): string {
  switch (object) {
    case MarketId.MARKET_UNKNOWN:
      return "MARKET_UNKNOWN";
    case MarketId.BTC_USDT:
      return "BTC_USDT";
    case MarketId.ETH_USDT:
      return "ETH_USDT";
    case MarketId.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Separate the Envelope from the Payload */
export interface ExchangeRequest {
  userId: number;
  /** Critical for measuring latency (T1) */
  timestamp: number;
  create?: CreateOrder | undefined;
  cancel?: CancelOrder | undefined;
  cancelAll?: CancelAll | undefined;
  deposit?: Deposit | undefined;
}

export interface CreateOrder {
  market: MarketId;
  price: string;
  quantity: string;
  side: Side;
  orderType: OrderType;
  /** For your MM mapping */
  clientId: number;
}

export interface CancelOrder {
  market: MarketId;
  /** The engine tries client_id first, then engine_id */
  clientId: number;
  engineId: number;
}

export interface CancelAll {
  market: MarketId;
}

export interface Deposit {
  /** "USDT" */
  asset: AssetId;
  amount: string;
  /** For idempotency */
  txId: number;
}

/** ====== OUT TYPES ========================================== */
export interface Trade {
  makerId: number;
  takerId: number;
  /** "100.50" */
  price: string;
  /** "0.001" */
  quantity: string;
  /** "buy" or "sell" */
  takerSide: Side;
  makerSide: Side;
  timestamp: number;
  market: MarketId;
  base: AssetId;
  quote: AssetId;
}

function createBaseExchangeRequest(): ExchangeRequest {
  return { userId: 0, timestamp: 0, create: undefined, cancel: undefined, cancelAll: undefined, deposit: undefined };
}

export const ExchangeRequest: MessageFns<ExchangeRequest> = {
  encode(message: ExchangeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).uint64(message.userId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).uint64(message.timestamp);
    }
    if (message.create !== undefined) {
      CreateOrder.encode(message.create, writer.uint32(26).fork()).join();
    }
    if (message.cancel !== undefined) {
      CancelOrder.encode(message.cancel, writer.uint32(34).fork()).join();
    }
    if (message.cancelAll !== undefined) {
      CancelAll.encode(message.cancelAll, writer.uint32(42).fork()).join();
    }
    if (message.deposit !== undefined) {
      Deposit.encode(message.deposit, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExchangeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExchangeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.create = CreateOrder.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cancel = CancelOrder.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.cancelAll = CancelAll.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.deposit = Deposit.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExchangeRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      create: isSet(object.create) ? CreateOrder.fromJSON(object.create) : undefined,
      cancel: isSet(object.cancel) ? CancelOrder.fromJSON(object.cancel) : undefined,
      cancelAll: isSet(object.cancelAll)
        ? CancelAll.fromJSON(object.cancelAll)
        : isSet(object.cancel_all)
        ? CancelAll.fromJSON(object.cancel_all)
        : undefined,
      deposit: isSet(object.deposit) ? Deposit.fromJSON(object.deposit) : undefined,
    };
  },

  toJSON(message: ExchangeRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.create !== undefined) {
      obj.create = CreateOrder.toJSON(message.create);
    }
    if (message.cancel !== undefined) {
      obj.cancel = CancelOrder.toJSON(message.cancel);
    }
    if (message.cancelAll !== undefined) {
      obj.cancelAll = CancelAll.toJSON(message.cancelAll);
    }
    if (message.deposit !== undefined) {
      obj.deposit = Deposit.toJSON(message.deposit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExchangeRequest>, I>>(base?: I): ExchangeRequest {
    return ExchangeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExchangeRequest>, I>>(object: I): ExchangeRequest {
    const message = createBaseExchangeRequest();
    message.userId = object.userId ?? 0;
    message.timestamp = object.timestamp ?? 0;
    message.create = (object.create !== undefined && object.create !== null)
      ? CreateOrder.fromPartial(object.create)
      : undefined;
    message.cancel = (object.cancel !== undefined && object.cancel !== null)
      ? CancelOrder.fromPartial(object.cancel)
      : undefined;
    message.cancelAll = (object.cancelAll !== undefined && object.cancelAll !== null)
      ? CancelAll.fromPartial(object.cancelAll)
      : undefined;
    message.deposit = (object.deposit !== undefined && object.deposit !== null)
      ? Deposit.fromPartial(object.deposit)
      : undefined;
    return message;
  },
};

function createBaseCreateOrder(): CreateOrder {
  return { market: 0, price: "", quantity: "", side: 0, orderType: 0, clientId: 0 };
}

export const CreateOrder: MessageFns<CreateOrder> = {
  encode(message: CreateOrder, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.market !== 0) {
      writer.uint32(8).int32(message.market);
    }
    if (message.price !== "") {
      writer.uint32(18).string(message.price);
    }
    if (message.quantity !== "") {
      writer.uint32(26).string(message.quantity);
    }
    if (message.side !== 0) {
      writer.uint32(32).int32(message.side);
    }
    if (message.orderType !== 0) {
      writer.uint32(40).int32(message.orderType);
    }
    if (message.clientId !== 0) {
      writer.uint32(48).uint64(message.clientId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrder {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrder();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.market = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.price = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.quantity = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.side = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.orderType = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.clientId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrder {
    return {
      market: isSet(object.market) ? marketIdFromJSON(object.market) : 0,
      price: isSet(object.price) ? globalThis.String(object.price) : "",
      quantity: isSet(object.quantity) ? globalThis.String(object.quantity) : "",
      side: isSet(object.side) ? sideFromJSON(object.side) : 0,
      orderType: isSet(object.orderType)
        ? orderTypeFromJSON(object.orderType)
        : isSet(object.order_type)
        ? orderTypeFromJSON(object.order_type)
        : 0,
      clientId: isSet(object.clientId)
        ? globalThis.Number(object.clientId)
        : isSet(object.client_id)
        ? globalThis.Number(object.client_id)
        : 0,
    };
  },

  toJSON(message: CreateOrder): unknown {
    const obj: any = {};
    if (message.market !== 0) {
      obj.market = marketIdToJSON(message.market);
    }
    if (message.price !== "") {
      obj.price = message.price;
    }
    if (message.quantity !== "") {
      obj.quantity = message.quantity;
    }
    if (message.side !== 0) {
      obj.side = sideToJSON(message.side);
    }
    if (message.orderType !== 0) {
      obj.orderType = orderTypeToJSON(message.orderType);
    }
    if (message.clientId !== 0) {
      obj.clientId = Math.round(message.clientId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrder>, I>>(base?: I): CreateOrder {
    return CreateOrder.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrder>, I>>(object: I): CreateOrder {
    const message = createBaseCreateOrder();
    message.market = object.market ?? 0;
    message.price = object.price ?? "";
    message.quantity = object.quantity ?? "";
    message.side = object.side ?? 0;
    message.orderType = object.orderType ?? 0;
    message.clientId = object.clientId ?? 0;
    return message;
  },
};

function createBaseCancelOrder(): CancelOrder {
  return { market: 0, clientId: 0, engineId: 0 };
}

export const CancelOrder: MessageFns<CancelOrder> = {
  encode(message: CancelOrder, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.market !== 0) {
      writer.uint32(8).int32(message.market);
    }
    if (message.clientId !== 0) {
      writer.uint32(16).uint64(message.clientId);
    }
    if (message.engineId !== 0) {
      writer.uint32(24).uint64(message.engineId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelOrder {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelOrder();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.market = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.clientId = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.engineId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CancelOrder {
    return {
      market: isSet(object.market) ? marketIdFromJSON(object.market) : 0,
      clientId: isSet(object.clientId)
        ? globalThis.Number(object.clientId)
        : isSet(object.client_id)
        ? globalThis.Number(object.client_id)
        : 0,
      engineId: isSet(object.engineId)
        ? globalThis.Number(object.engineId)
        : isSet(object.engine_id)
        ? globalThis.Number(object.engine_id)
        : 0,
    };
  },

  toJSON(message: CancelOrder): unknown {
    const obj: any = {};
    if (message.market !== 0) {
      obj.market = marketIdToJSON(message.market);
    }
    if (message.clientId !== 0) {
      obj.clientId = Math.round(message.clientId);
    }
    if (message.engineId !== 0) {
      obj.engineId = Math.round(message.engineId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelOrder>, I>>(base?: I): CancelOrder {
    return CancelOrder.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelOrder>, I>>(object: I): CancelOrder {
    const message = createBaseCancelOrder();
    message.market = object.market ?? 0;
    message.clientId = object.clientId ?? 0;
    message.engineId = object.engineId ?? 0;
    return message;
  },
};

function createBaseCancelAll(): CancelAll {
  return { market: 0 };
}

export const CancelAll: MessageFns<CancelAll> = {
  encode(message: CancelAll, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.market !== 0) {
      writer.uint32(8).int32(message.market);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelAll {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelAll();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.market = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CancelAll {
    return { market: isSet(object.market) ? marketIdFromJSON(object.market) : 0 };
  },

  toJSON(message: CancelAll): unknown {
    const obj: any = {};
    if (message.market !== 0) {
      obj.market = marketIdToJSON(message.market);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelAll>, I>>(base?: I): CancelAll {
    return CancelAll.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelAll>, I>>(object: I): CancelAll {
    const message = createBaseCancelAll();
    message.market = object.market ?? 0;
    return message;
  },
};

function createBaseDeposit(): Deposit {
  return { asset: 0, amount: "", txId: 0 };
}

export const Deposit: MessageFns<Deposit> = {
  encode(message: Deposit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.asset !== 0) {
      writer.uint32(8).int32(message.asset);
    }
    if (message.amount !== "") {
      writer.uint32(18).string(message.amount);
    }
    if (message.txId !== 0) {
      writer.uint32(24).uint64(message.txId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Deposit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeposit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.asset = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.txId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Deposit {
    return {
      asset: isSet(object.asset) ? assetIdFromJSON(object.asset) : 0,
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      txId: isSet(object.txId)
        ? globalThis.Number(object.txId)
        : isSet(object.tx_id)
        ? globalThis.Number(object.tx_id)
        : 0,
    };
  },

  toJSON(message: Deposit): unknown {
    const obj: any = {};
    if (message.asset !== 0) {
      obj.asset = assetIdToJSON(message.asset);
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.txId !== 0) {
      obj.txId = Math.round(message.txId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Deposit>, I>>(base?: I): Deposit {
    return Deposit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Deposit>, I>>(object: I): Deposit {
    const message = createBaseDeposit();
    message.asset = object.asset ?? 0;
    message.amount = object.amount ?? "";
    message.txId = object.txId ?? 0;
    return message;
  },
};

function createBaseTrade(): Trade {
  return {
    makerId: 0,
    takerId: 0,
    price: "",
    quantity: "",
    takerSide: 0,
    makerSide: 0,
    timestamp: 0,
    market: 0,
    base: 0,
    quote: 0,
  };
}

export const Trade: MessageFns<Trade> = {
  encode(message: Trade, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.makerId !== 0) {
      writer.uint32(8).uint64(message.makerId);
    }
    if (message.takerId !== 0) {
      writer.uint32(16).uint64(message.takerId);
    }
    if (message.price !== "") {
      writer.uint32(26).string(message.price);
    }
    if (message.quantity !== "") {
      writer.uint32(34).string(message.quantity);
    }
    if (message.takerSide !== 0) {
      writer.uint32(40).int32(message.takerSide);
    }
    if (message.makerSide !== 0) {
      writer.uint32(48).int32(message.makerSide);
    }
    if (message.timestamp !== 0) {
      writer.uint32(56).uint64(message.timestamp);
    }
    if (message.market !== 0) {
      writer.uint32(64).int32(message.market);
    }
    if (message.base !== 0) {
      writer.uint32(72).int32(message.base);
    }
    if (message.quote !== 0) {
      writer.uint32(80).int32(message.quote);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Trade {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrade();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.makerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.takerId = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.price = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.quantity = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.takerSide = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.makerSide = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.market = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.base = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.quote = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Trade {
    return {
      makerId: isSet(object.makerId)
        ? globalThis.Number(object.makerId)
        : isSet(object.maker_id)
        ? globalThis.Number(object.maker_id)
        : 0,
      takerId: isSet(object.takerId)
        ? globalThis.Number(object.takerId)
        : isSet(object.taker_id)
        ? globalThis.Number(object.taker_id)
        : 0,
      price: isSet(object.price) ? globalThis.String(object.price) : "",
      quantity: isSet(object.quantity) ? globalThis.String(object.quantity) : "",
      takerSide: isSet(object.takerSide)
        ? sideFromJSON(object.takerSide)
        : isSet(object.taker_side)
        ? sideFromJSON(object.taker_side)
        : 0,
      makerSide: isSet(object.makerSide)
        ? sideFromJSON(object.makerSide)
        : isSet(object.maker_side)
        ? sideFromJSON(object.maker_side)
        : 0,
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      market: isSet(object.market) ? marketIdFromJSON(object.market) : 0,
      base: isSet(object.base) ? assetIdFromJSON(object.base) : 0,
      quote: isSet(object.quote) ? assetIdFromJSON(object.quote) : 0,
    };
  },

  toJSON(message: Trade): unknown {
    const obj: any = {};
    if (message.makerId !== 0) {
      obj.makerId = Math.round(message.makerId);
    }
    if (message.takerId !== 0) {
      obj.takerId = Math.round(message.takerId);
    }
    if (message.price !== "") {
      obj.price = message.price;
    }
    if (message.quantity !== "") {
      obj.quantity = message.quantity;
    }
    if (message.takerSide !== 0) {
      obj.takerSide = sideToJSON(message.takerSide);
    }
    if (message.makerSide !== 0) {
      obj.makerSide = sideToJSON(message.makerSide);
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.market !== 0) {
      obj.market = marketIdToJSON(message.market);
    }
    if (message.base !== 0) {
      obj.base = assetIdToJSON(message.base);
    }
    if (message.quote !== 0) {
      obj.quote = assetIdToJSON(message.quote);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Trade>, I>>(base?: I): Trade {
    return Trade.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Trade>, I>>(object: I): Trade {
    const message = createBaseTrade();
    message.makerId = object.makerId ?? 0;
    message.takerId = object.takerId ?? 0;
    message.price = object.price ?? "";
    message.quantity = object.quantity ?? "";
    message.takerSide = object.takerSide ?? 0;
    message.makerSide = object.makerSide ?? 0;
    message.timestamp = object.timestamp ?? 0;
    message.market = object.market ?? 0;
    message.base = object.base ?? 0;
    message.quote = object.quote ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
