use std::collections::HashMap;

use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use sqlx::{prelude::FromRow, types::chrono::{DateTime, Utc}};
use deadpool_redis::Pool as RedisPool;
use sqlx::PgPool;

use crate::{model::exchange_proto::{ExchangeRequest, MarketId, exchange_request::Action}, utils::MarketConfig};

#[derive(Serialize)]
pub struct Status {
    pub active : bool,
    pub engine_tps : u64
}

#[derive(Clone)] // clonable state for different green threads
pub struct AppState {
    pub db : PgPool,
    pub redis: RedisPool,
    pub markets: HashMap<MarketId, MarketConfig>
}
#[derive(Deserialize)]
pub struct SeedRequest {
    pub user_id: i64,
    pub asset: String,     // Matches your 'asset' column
    pub available: Decimal, // Matches NUMERIC
    pub locked: Option<Decimal>,
}

#[derive(Debug, Serialize, Deserialize,FromRow)]
pub struct Kline {
    pub bucket: DateTime<Utc>,
    pub open: Decimal,
    pub high: Decimal,
    pub low: Decimal,
    pub close: Decimal,
    pub volume: Decimal,
}

#[derive(Deserialize, Debug)]
pub struct KlineParams {
    pub symbol: i64,
    pub interval: String, // e.g., "1m", "1h"
    pub limit : i64
}

#[derive(Deserialize, Debug)]
pub struct GetOpenOrderByUserIdParams {
    pub userid : i64,
    pub symbol : String
}

// 1. Order Request struct
#[derive(Debug, Clone)]
pub struct OrderRequest {
    pub user_id : u64,
    pub market : MarketId,
    pub side : Side,
    pub price : Option<Decimal>,
    pub quantity : Option<Decimal>,
    pub order_type : OrderType,
    pub action : ActionType,
    pub client_id : Option<u64>,
    pub engine_id : Option<u64>,
    pub timestamp : u64
}

#[derive(Debug)]
// The Internal "Resting" Order
pub struct Order {
    pub engine_id: u64,
    pub client_id : u64,
    pub user_id: u64,
    pub price: Decimal,
    pub quantity: Decimal,
    pub side: Side,
    pub timestamp: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Deserialize, Serialize)]
pub enum Side { Buy, Sell }

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum OrderType { Limit, Market }

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ActionType { Create, Cancel, CancelAll, Deposit }

// --- 2. THE GENERATED TYPES ---
pub mod exchange_proto {
    // This pulls in the code generated by build.rs in the target folder
    include!(concat!(env!("OUT_DIR"), "/exchange.rs"));
}

// Bring the Proto types into local scope for the TryFrom logic
// 'exchange' refers to the 'package exchange;' line in your .proto
// --- 3. THE FIREWALL (Conversion Logic) ---
impl TryFrom<ExchangeRequest> for OrderRequest {
    type Error = String;

    fn try_from(proto: ExchangeRequest) -> Result<Self, Self::Error> {
        let user_id = proto.user_id;
        let timestamp = proto.timestamp;

        // Extract the oneof action
        let action_payload = proto.action.ok_or("No action provided in request")?;

        match action_payload {
            // Case: Creating a new Order
            Action::Create(c) => Ok(OrderRequest {
                user_id,
                timestamp,
                market: c.market(),
                side: if c.side == 0 { Side::Buy } else { Side::Sell },
                price: Some(Decimal::from_str_exact(&c.price).map_err(|_| "Invalid Price Format")?),
                quantity: Some(Decimal::from_str_exact(&c.quantity).map_err(|_| "Invalid Qty Format")?),
                order_type: if c.order_type == 0 { OrderType::Limit } else { OrderType::Market },
                action: ActionType::Create,
                client_id: Some(c.client_id),
                engine_id: None,
            }),

            // Case: Cancelling an existing Order
            Action::Cancel(c) => Ok(OrderRequest {
                user_id,
                timestamp,
                market: c.market(),
                side: Side::Buy, // Placeholder (not used for cancel)
                price: None,
                quantity: None,
                order_type: OrderType::Limit,
                action: ActionType::Cancel,
                client_id: if c.client_id != 0 { Some(c.client_id) } else { None },
                engine_id: if c.engine_id != 0 { Some(c.engine_id) } else { None },
            }),

            // Case: expand this later
            Action::Deposit(_) => Err("Deposit logic belongs in the Bank module".to_string()),
            
            _ => Err("Unsupported action pub type".to_string()),
        }
    }

    
}


impl ExchangeRequest {
    /// Peeks at the inner action to find which market this request belongs to.
    pub fn get_market(&self) -> Option<MarketId> {
        match &self.action {
            Some(Action::Create(c)) => Some(c.market()),
            Some(Action::Cancel(c)) => Some(c.market()),
            Some(Action::CancelAll(c)) => Some(c.market()),
            _ => None, // Deposits are usually market-agnostic (account level)
        }
    }
}