use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

use crate::{candle::Candle, model::exchange_proto::{DepthUpdate, Trade}};



// --- 2. THE GENERATED TYPES ---
pub mod exchange_proto {
    // This pulls in the code generated by build.rs in the target folder
    include!(concat!(env!("OUT_DIR"), "/exchange.rs"));
}

#[derive(Debug, Serialize, Deserialize)]
pub struct InternalTrade {
    pub price : f64,
    pub quantity : f64,
    pub timestamp : u64
}

impl InternalTrade {
    pub fn from_proto(proto : Trade) -> Self {
        Self { 
            price: proto.price.parse::<f64>().unwrap_or(0.0), 
            quantity: proto.quantity.parse::<f64>().unwrap_or(0.0),
            timestamp : proto.timestamp
        }
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Depth {
    pub market: u64,
    pub bids: Vec<Level>,
    pub asks: Vec<Level>,
    pub timestamp : u64
}

impl Depth {
    pub fn from_proto(proto: DepthUpdate) -> Self {
        Self { 
            // Parsing market ID from string to u64
            market: proto.market as u64,     
                   
            // 2. Use .parse() or Decimal::from_str()
            bids: proto.bids.into_iter().map(|l| Level {
                price: l.price.parse::<Decimal>().unwrap_or_default(),
                quantity: l.quantity.parse::<Decimal>().unwrap_or_default(),
            }).collect(),

            asks: proto.asks.into_iter().map(|l| Level {
                price: l.price.parse::<Decimal>().unwrap_or_default(),
                quantity: l.quantity.parse::<Decimal>().unwrap_or_default(),
            }).collect(),

            timestamp: proto.timestamp as u64,
        }
    }
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "method", content = "params", rename_all = "lowercase")]
pub enum WsRequest {
    Subscribe { 
        market: String, 
        stream: String // "candles_1m", "candles_5m", or "depth"
    },
    Unsubscribe { 
        market: String,
        stream: String 
    },
    // This is for private updates
    UserUpdates { 
        user_id: String 
    },
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "stream", content = "data", rename_all = "lowercase")]
pub enum WsOutMessage {
    // Realtime trade updates
    Trade(InternalTrade),

    // the ohlcv
    Candle(Candle),

    // Ticker 
    Ticker {
        market : String, 
        last_price : f64,
        price_change_percent: f64,
        volume_24h : f64
    },

    Depth(Depth)
}


// =========== Depth event ==========================

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Level {
    pub price: Decimal,
    pub quantity: Decimal,
}
