use serde::{Deserialize, Serialize};

use crate::{candle::Candle, model::exchange_proto::Trade};



// --- 2. THE GENERATED TYPES ---
pub mod exchange_proto {
    // This pulls in the code generated by build.rs in the target folder
    include!(concat!(env!("OUT_DIR"), "/exchange.rs"));
}

#[derive(Debug, Serialize, Deserialize)]
pub struct InternalTrade {
    pub price : f64,
    pub quantity : f64,
    pub timestamp : u64
}

impl InternalTrade {
    pub fn from_proto(proto : Trade) -> Self {
        Self { 
            price: proto.price.parse::<f64>().unwrap_or(0.0), 
            quantity: proto.quantity.parse::<f64>().unwrap_or(0.0),
            timestamp : proto.timestamp
        }
    }
}


#[derive(Deserialize)]
#[serde(tag = "method", content = "params", rename_all = "lowercase")]
pub enum WsRequest {
    Subscribe { market: String },
    Unsubscribe { market: String },
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "stream", content = "data", rename_all = "lowercase")]
pub enum WsOutMessage {
    // Realtime trade updates
    Trade(InternalTrade),

    // the ohlcv
    Candle(Candle),

    // Ticker 
    Ticker {
        market : String, 
        last_price : f64,
        price_change_percent: f64,
        volume_24h : f64
    }
}