use rust_decimal::Decimal;
use crate::model::exchange_proto::{ExchangeRequest, exchange_request::Action};

// 1. Order Request struct
#[derive(Debug)]
pub struct OrderRequest {
    pub user_id : u64,
    pub symbol : String,
    pub side : Side,
    pub price : Option<Decimal>,
    pub quantity : Option<Decimal>,
    pub order_type : OrderType,
    pub action : ActionType,
    pub client_id : Option<u64>,
    pub engine_id : Option<u64>,
    pub timestamp : u64
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Side { Buy, Sell }

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum OrderType { Limit, Market }

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ActionType { Create, Cancel, CancelAll, Deposit }

// --- 2. THE GENERATED TYPES ---
pub mod exchange_proto {
    // This pulls in the code generated by build.rs in the target folder
    include!(concat!(env!("OUT_DIR"), "/exchange.rs"));
}

// Bring the Proto types into local scope for the TryFrom logic
// 'exchange' refers to the 'package exchange;' line in your .proto

// ---- 3. The Firewall (Conversion Logic) ----
impl TryFrom<ExchangeRequest> for OrderRequest {
    
    type Error = String;
    fn try_from(proto: ExchangeRequest) -> Result<Self, Self::Error> {
        let user_id = proto.user_id;
        let timestamp = proto.timestamp;

        // Extract the oneof action
        let action = proto.action.ok_or("No action provided in request");

        match action_payload {
            // Case: Creating a new Order
            Action::Create(c) => Ok(OrderRequest {
                user_id,
                timestamp,
                symbol: c.symbol,
                side: if c.side == 0 { Side::Buy } else { Side::Sell },
                price: Some(Decimal::from_str(&c.price).map_err(|_| "Invalid Price Format")?),
                quantity: Some(Decimal::from_str(&c.quantity).map_err(|_| "Invalid Qty Format")?),
                order_type: if c.order_type == 0 { OrderType::Limit } else { OrderType::Market },
                action: ActionType::Create,
                client_id: Some(c.client_id),
                engine_id: None,
            }),

            // Case: Cancelling an existing Order
            Action::Cancel(c) => Ok(OrderRequest {
                user_id,
                timestamp,
                symbol: c.symbol,
                side: Side::Buy, // Placeholder (not used for cancel)
                price: None,
                quantity: None,
                order_type: OrderType::Limit,
                action: ActionType::Cancel,
                client_id: if c.client_id != 0 { Some(c.client_id) } else { None },
                engine_id: if c.engine_id != 0 { Some(c.engine_id) } else { None },
            }),

            // Case: Deposit (You can expand this later)
            Action::Deposit(_) => Err("Deposit logic belongs in the Bank module".to_string()),
            
            _ => Err("Unsupported action type".to_string()),
        }
    }
}